### ISSUE TITLE
EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE

### ISSUE THREAD

**Issue by jyothishkm** [terrabythia/flutter_chromecast_example#7]
I clone the project and get the dependency after run app not crash but in console showing the error "EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE" i am not able to cast.

**Comment by jyothishkm** [comment]
EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (31788): The following HandshakeException was thrown resolving an image codec:
I/flutter (31788): Connection terminated during handshake
I/flutter (31788): 
I/flutter (31788): When the exception was thrown, this was the stack:
I/flutter (31788): #0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:84:41)
I/flutter (31788): <asynchronous suspension>
I/flutter (31788): #1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:48:14)
I/flutter (31788): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:48)
I/flutter (31788): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (31788): #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:25)
I/flutter (31788): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (31788): #6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:313:11)
I/flutter (31788): #10     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:305:16)
I/flutter (31788): #11     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:951:20)
I/flutter (31788): #12     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:908:5)
I/flutter (31788): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
I/flutter (31788): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
I/flutter (31788): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (31788): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (31788): #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (31788): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #79     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #88     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #97     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #103    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (31788): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #113    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #116    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (31788): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #121    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #129    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4314:11)
I/flutter (31788): #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #135    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter (31788): #136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (31788): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (31788): #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (31788): #141    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter (31788): #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (31788): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
D/GraphicBuffer(31788): register, handle(0xe4323060) (w:1080 h:1920 s:1088 f:0x1 u:b00)
I/flutter (31788): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (31788): #145    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
I/flutter (31788): #146    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:20)
I/flutter (31788): #147    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
I/flutter (31788): #148    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
I/flutter (31788): #149    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
I/flutter (31788): #150    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
I/flutter (31788): #151    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
I/flutter (31788): #152    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
I/flutter (31788): #153    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
I/flutter (31788): #154    RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
I/flutter (31788): #155    RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
I/flutter (31788): #156    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
I/flutter (31788): #157    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #158    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter (31788): #159    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #160    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter (31788): #161    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1352:12)
I/flutter (31788): #162    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1270:20)
I/flutter (31788): #163    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #164    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #165    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #166    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #167    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #168    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #169    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #170    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #171    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #172    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #173    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #174    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #175    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #176    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #177    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #178    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #179    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #180    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #181    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #182    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (31788): #183    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #184    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (31788): #185    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:444:7)
I/flutter (31788): #186    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (31788): #187    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (31788): #188    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #189    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #190    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #191    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #192    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
I/flutter (31788): #193    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #194    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #195    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #196    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #197    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #198    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #199    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #200    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #201    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #202    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #203    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #204    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #205    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #206    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #207    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #208    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #209    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3140:13)
I/flutter (31788): #210    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #211    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (31788): #212    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #213    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #214    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #215    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #216    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #217    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #218    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #219    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #220    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #221    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #222    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #223    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (31788): #224    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
I/flutter (31788): #225    RenderView.performLayout (package:flutter/src/rendering/view.dart:152:13)
I/flutter (31788): #226    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578:7)
I/flutter (31788): #227    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
I/flutter (31788): #228    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:341:19)
I/flutter (31788): #229    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:13)
I/flutter (31788): #230    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
I/flutter (31788): #231    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter (31788): #232    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter (31788): #233    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter (31788): #242    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (31788): #243    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (31788): #244    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (31788): (elided 11 frames from package dart:async and package dart:async-patch)
I/flutter (31788): 
I/flutter (31788): Image provider: NetworkImage("https://i.ytimg.com/vi/YlYCO2VLUEc/maxresdefault.jpg", scale: 1.0)
I/flutter (31788): Image key: NetworkImage("https://i.ytimg.com/vi/YlYCO2VLUEc/maxresdefault.jpg", scale: 1.0)
I/flutter (31788): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31788): Another exception was thrown: HandshakeException: Connection terminated during handshake
Lost connection to device.
